default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Weathra")
    upload_to_testflight
  end

  desc "Run tests"
  lane :test do
    run_tests(scheme: "WeathraTests")
  end
end
